global:
  scrape_interval: 5s
 
scrape_configs:
  # OTEL Collector expondo m√©tricas via Prometheus exporter
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
